/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.keepass;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int keepass_icon=0x7f020000;
    }
    public static final class id {
        public static final int entry_comment=0x7f050004;
        public static final int entry_password=0x7f050003;
        public static final int entry_title=0x7f050000;
        public static final int entry_url=0x7f050002;
        public static final int entry_user_name=0x7f050001;
        public static final int pass_filename=0x7f050005;
        public static final int pass_ok=0x7f050007;
        public static final int pass_password=0x7f050006;
        public static final int text1=0x7f050008;
    }
    public static final class layout {
        public static final int entry_view=0x7f030000;
        public static final int list=0x7f030001;
        public static final int password=0x7f030002;
        public static final int row=0x7f030003;
    }
    public static final class string {
        public static final int FileNotFound=0x7f040002;
        public static final int InvalidPassword=0x7f040003;
        public static final int MaskedPassword=0x7f04000a;
        public static final int app_name=0x7f040000;
        public static final int entry_comment=0x7f040009;
        public static final int entry_password=0x7f040008;
        public static final int entry_title=0x7f040005;
        public static final int entry_url=0x7f040007;
        public static final int entry_user_name=0x7f040006;
        public static final int menu_copy_pass=0x7f04000f;
        public static final int menu_copy_url=0x7f04000d;
        public static final int menu_copy_user=0x7f04000e;
        public static final int menu_hide_password=0x7f04000c;
        public static final int menu_show_password=0x7f04000b;
        public static final int no_keys=0x7f040001;
        public static final int pass_filename=0x7f040010;
        public static final int pass_ok=0x7f040004;
    }
}
