name: Feature request
description: Suggest an idea.
title: ""
labels: feature
body:
  - type: markdown
    attributes:
      value: |
        Please check out the [Wiki](https://github.com/Kunzisoft/KeePassDX/wiki) and [existing issues](https://github.com/Kunzisoft/KeePassDX/issues?q=is%3Aissue%20state%3Aopen%20label%3Afeature) to see if your feature has already been reported.
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have read the Wiki, searched the open issues, and still think this is a new feature.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: "Explain the problem clearly and succinctly:"
  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like:"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered:"
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context:"
