#!/bin/sh

DEFAULT=debug

WHICH=${1:-${DEFAULT}}
shift

echo Using config $WHICH

case $WHICH in
    clang)
	PATH=$PATH:/home/ben/svn-work/llvm/Debug/bin /home/ben/svn-work/llvm/tools/clang/utils/scan-build ./config -debug
	;;

    debug)
	./Configure debug-ben-debug
	;;

    no-renegotiation)
	./Configure debug-ben-no-renegotiation
	;;

    no-fips)
	./config no-fips
	;;

    camellia)
	./Configure debug-ben-debug enable-camellia
	;;

    *)
	echo Config $WHICH unknown!
	exit 1
	;;
esac


#./config -d -Wall -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Werror -DDEBUG_SAFESTACK -DCRYPTO_MDEBUG
#perl -pi.bak - `find . -name Makefile` <<EOF
#s/^CC=\s*gcc\s*$/CC=gcc34\n/;
#EOF

#./config -d -Wall -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Werror -DDEBUG_SAFESTACK -DCRYPTO_MDEBUG -DPURIFY -DPEDANTIC -pedantic  -Wno-long-long fips $@
#./config enable-jpake -d -Wall -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Werror -DDEBUG_SAFESTACK -DCRYPTO_MDEBUG -DPURIFY -DPEDANTIC -pedantic -Wno-long-long $@ 
#./config -d -Wall -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Werror -DDEBUG_SAFESTACK -DCRYPTO_MDEBUG -DPURIFY -DPEDANTIC -pedantic -Wno-long-long $@ 
#./config -d -Wall -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Werror -DDEBUG_SAFESTACK -DPURIFY -DPEDANTIC -pedantic -Wno-long-long enable-rfc3779 $@
#./config -d -Wall -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Werror -DDEBUG_SAFESTACK -DCRYPTO_MDEBUG -DPEDANTIC -pedantic -Wno-long-long $@ 

#CC=/home/ben/svn-work/llvm/tools/clang/utils/ccc-analyzer ./config
#PATH=$PATH:/home/ben/svn-work/llvm/Debug/bin /home/ben/svn-work/llvm/tools/clang/utils/scan-build ./config

#perl -pi.bak - `find . -name Makefile` <<EOF
#s/^CC=\s*gcc\s*$/CC=\\\$(HOME)\/svn-work\/llvm\/tools\/clang\/utils\/ccc\n/;
#EOF
#perl -pi.bak - `find . -name Makefile` <<EOF
#s/^CC=\s*gcc\s*$/CC=\\\$(HOME)\/svn-work\/llvm\/tools\/clang\/utils\/ccc-analyzer\n/;
#EOF
