package com.kunzisoft.keepass.biometric

enum class DeviceUnlockMode {
    BIOMETRIC_UNAVAILABLE,
    BIOMETRIC_SECURITY_UPDATE_REQUIRED,
    DEVICE_CREDENTIAL_OR_BIOMETRIC_NOT_CONFIGURED,
    KEY_MANAGER_UNAVAILABLE,
    WAIT_CREDENTIAL,
    STORE_CREDENTIAL,
    EXTRACT_CREDENTIAL
}